### ISSUE TITLE
PCA didn't use pcaMapping information

### ISSUE THREAD

**Issue by gktharp1** [yerkes-gencore/gencoreBulk#11]
PCA didn't use the color, shape, label, and path information I specified in QC_config.yaml

**Comment by derrik-gratz** [comment]
I've had this issue once too, but I believe it is resolved now with the update, and we tested it with your latest pull too and it worked, it might have just been an older version. Leaving open fornow until we confirm it consistently works

**Comment by derrik-gratz** [comment]
This does seem to be resolved, I haven't had issues with it in a while
